### ISSUE TITLE
In welke taal is je pagina geschreven?

### ISSUE THREAD

**Issue by krijnhoetmer** [Metehan2003/fix-the-flow-interactive-website#3]
Probeer dat aan te geven via [het `lang` attribuut](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang).

https://github.com/Metehan2003/fix-the-flow-interactive-website/blob/9bc40f2a629270ff90fe4025d8611c0e3dad4940/index.html#L2

**Comment by Metehan2003** [comment]
Ik heb lang=en erin gezet

**Comment by krijnhoetmer** [comment]
Is je website in het Engels dan?

**Comment by Metehan2003** [comment]
Mijn site is in het Nederlands maar de code is in het Engels. Ik raakte even in de war.
Ik heb nu lang=nl erin gezet.

**Comment by krijnhoetmer** [comment]
Goedzo, het gaat om de taal van de content inderdaad, niet je code (dat is niet wat eindgebruikers/mensen lezen of voorgelezen krijgen :)
