### ISSUE TITLE
Wat betekent een alinea in een heading?

### ISSUE THREAD

**Issue by krijnhoetmer** [Metehan2003/fix-the-flow-interactive-website#4]
Zie https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements voor meer informatie.

https://github.com/Metehan2003/fix-the-flow-interactive-website/blob/9bc40f2a629270ff90fe4025d8611c0e3dad4940/index.html#L18

**Comment by Metehan2003** [comment]
De alinea's waren niet nodig in de headings. Ik heb ze nu weggehaald.
