### ISSUE TITLE
Heb je hier echt een line break nodig?

### ISSUE THREAD

**Issue by krijnhoetmer** [Metehan2003/fix-the-flow-interactive-website#5]
Zie https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br — is extra witruimte niet iets wat je beter met CSS kunt oplossen?

https://github.com/Metehan2003/fix-the-flow-interactive-website/blob/9bc40f2a629270ff90fe4025d8611c0e3dad4940/index.html#L20

**Comment by Metehan2003** [comment]
Ik heb nu witruimte met margin geregeld.
